@startuml red_nueva
skinparam backgroundColor #ffffff
skinparam shadowing false

skinparam node {
  BackgroundColor #f7f7f7
  BorderColor #555555
}
skinparam cloud {
  BackgroundColor #eef6ff
  BorderColor #356ac3
}
skinparam rectangle {
  BackgroundColor #fefefe
  BorderColor #888
}

skinparam node<<Gateway>> {
  BackgroundColor #e8f0fe
  BorderColor #1a73e8
}

skinparam node<<MainRouting>> {
  BackgroundColor #ffdd009b
  BorderColor #bda400ff
}

skinparam node<<Switch>> {
  BackgroundColor #fea546d3
  BorderColor #d47006ff
}

skinparam node<<AP>> {
  BackgroundColor #019f0e44
  BorderColor #009c0dFF
}

skinparam node<<Server>> {
  BackgroundColor #fe4646d3
  BorderColor rgb(212, 6, 6)
}

title Red del Colegio Propuesta

cloud "Internet\n200 Mbps simétricos" as inet

node "Modem" as modem
inet -d-> modem


node "DNS" as dns_srv <<Server>>

node "Multiuso" as fat_srv <<Server>>

node "Network Management" as mgmt_srv <<Server>>

node "Mikrotik CCR2004-16G-2S+" as sw_inet <<MainRouting>>

node "Primer ciclo" as primer_ciclo

node "Estacion VOIP" as voip

modem -d-> sw_inet
modem -d-> primer_ciclo

sw_inet -d-> dns_srv
sw_inet -d-> fat_srv
sw_inet -d-> mgmt_srv
sw_inet -d-> voip


node "Switch Lab 1 (Prog)" as lab1_prog

node "Mikrotik LAB1 Prog" as mt_lab1_prog <<Gateway>>

node "Router Electronica" as mt_lab2_electronica <<Gateway>>

node "Switch Lab 2 (Electronica)" as lab2_electronica

node "Switch Lab 1 (Electronica)" as lab1_electronica

node "Switch Lab 2 (Prog)" as lab2_prog

node "Switch Lab FAT (Prog)" as lab_fat_prog

node "Switch Lab Redes (Prog)" as lab_redes_prog

node "Mikrotik WiFi LAB2 Prog" as mt_lab2_prog <<Gateway>>

node "Mikrotik WiFi LAB FAT Prog" as mt_fat_prog  <<Gateway>>

node "Mikrotik Redes Prog" as mt_redes_prog <<Gateway>>

node "Switch Lab 3 (Prog)" as lab3_prog

node "Switch Ajuste" as lab_ajuste

node "PC DHCP" as mt_lab3_prog <<Gateway>>

node "Switch Admin" as sw_admin

node "RED-ITSV-COMUNIDAD AP*1" as comunidad <<AP>>

node "RED-ITSV AP*2" as red_itsv_p1 <<AP>>

node "Mikrotik WIFI ADMIN" as mt_admin <<Gateway>>

node "Switch Piso 1" as sw_piso1  <<Switch>>

node "Switch Planta Baja" as sw_pb <<Switch>>

node "RED-ITSV AP*8" as red_itsv_pb <<AP>>



sw_inet -d-> mt_lab2_prog
sw_inet -d-> mt_fat_prog
sw_inet -d-> mt_redes_prog
sw_inet -d-> sw_piso1
sw_inet -d-> sw_pb
sw_inet -d-> mt_lab1_prog
sw_inet -d-> mt_lab3_prog
sw_inet -d-> mt_admin


mt_lab1_prog -d-> lab1_prog
mt_lab2_electronica -d-> lab2_electronica
mt_fat_prog -d-> lab_fat_prog
mt_lab2_prog -d-> lab2_prog
mt_redes_prog -d-> lab_redes_prog
mt_lab3_prog -d-> lab3_prog
lab3_prog -d-> lab_ajuste
lab3_prog -d-> wifi
mt_admin -d-> sw_admin
mt_lab2_electronica -d-> lab1_electronica


lab2_prog -d-> comunidad
sw_piso1 -d-> mt_lab2_electronica
sw_piso1 -d-> red_itsv_p1
sw_pb -d-> electricidad
sw_pb -d-> red_itsv_pb

lab2_electronica -d-> soldadura


@enduml
