services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    # Recursos
    cpus: 2
    mem_limit: 2g

    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port
      - "443:443/tcp"
      # Uncomment if using Pi-hole as DHCP server
      # - "67:67/udp"
      # Uncomment if using Pi-hole as NTP server
      # - "123:123/udp"

    environment:
      TZ: 'America/Argentina/Cordoba'
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      FTLCONF_dns_listeningMode: 'ALL'

    volumes:
      - './etc-pihole:/etc/pihole'
      # - './etc-dnsmasq.d:/etc/dnsmasq.d'

    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

    restart: unless-stopped